name: Run Tests and Generate Allure Report

on:
  pull_request:
    branches: ['*']
  workflow_dispatch:
    inputs:
      tests:
        type: choice
        description: 'Select test type: test_episode, test_id, test_location'
        default: 'test_episode'
        options:
          - test_episode
          - test_id
          - test_location

jobs:
  run_tests_and_generate_report:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        test_type:
          - episode
          - id
          - location
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.1

      - name: Install dependencies from requirements.txt
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/test_${{ matrix.test_type }}.py

      - name: Load test report history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: allure-results
          allure_history: allure-history

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

  run_tests_manually:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.1'

      - name: Install dependencies from requirements.txt
        run: pip install -r requirements.txt

      - name: Run selected test
        run: pytest tests/${{ github.event.inputs.tests }}.py
