name: Run Tests

on:
  pull_request:
    branches: ['*']
  workflow_dispatch:
    inputs:
      tests:
        type: choice
        description: 'Select test type: test_episode, test_id, test_location'
        default: 'test_episode'
        options:
          - test_episode
          - test_id
          - test_location

jobs:
  run_tests_on_pr:
    if: ${{ github.event_name == 'pull_request' }}
    strategy:
      matrix:
        test_type:
          - episode
          - id
          - location
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create and activate virtual environment
        run: |
          python3.9 -m venv myenv
          source myenv/bin/activate

      - name: Install dependencies from requirements.txt
        run: pip install -r requirements.txt

      - name: Install allure-pytest
        run: pip install allure-pytest==2.13.2

      - name: Run tests
        run: pytest tests/test_${{ matrix.test_type }}.py

  run_tests_manually:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create and activate virtual environment
        run: |
          python3.9 -m venv myenv
          source myenv/bin/activate

      - name: Install dependencies from requirements.txt
        run: pip install -r requirements.txt

      - name: Install allure-pytest
        run: pip install allure-pytest==2.13.2

      - name: Run selected test
        run: pytest tests/${{ github.event.inputs.tests }}.py
