name: Run Tests Manual Workflow

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Select test type'
        required: false
        default: 'id'
        options:
          - episode
          - id
          - location

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.1

      - name: Install dependencies from requirements.txt
        run: pip install -r requirements.txt

      - name: Determine Test Type
        id: set_test_type
        run: echo "TEST_TYPE=${{ inputs.test_type || 'episode' }}" >> $GITHUB_ENV

      - name: Run selected test
        run: pytest tests/test_${{ env.TEST_TYPE }}.py
