name: Linters

on:
  pull_request:

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.12

      - name: Install project dependencies and run pylint
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pylint **/*.py || true