name: Run tests on PRs

on:
  pull_request:
    branches:
      - '*'

jobs:
  run_tests:
    strategy:
      matrix:
        test_type:
          - episode
          - id
          - location

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies from requirements.txt
      run: pip install -r requirements.txt

    - name: Run tests for R&M ${matrix.test_type^}
      run: pytest tests/test_${{ matrix.test_type }}.py
