name: Run Tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_type: ['test_episode', 'test_id', 'test_location']

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.1

    - name: Install dependencies from requirements.txt
      run: pip install -r requirements.txt

    - name: Run tests
      run: python3 tests/${{ matrix.test_type }}.py
