name: Tests

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Select the type of test to run'
        required: false
        type: choice
        options:
          - episode
          - id
          - location

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.1'

    - name: Install dependencies from requirements.txt
      run: pip install -r requirements.txt

    - name: Run selected test (manual trigger)
      if: github.event_name == 'workflow_dispatch'
      run: pytest tests/test_${{ github.event.inputs.test_type }}.py

    - name: Run all tests (pull request trigger)
      if: github.event_name == 'pull_request'
      run: |
        pytest tests/test_episode.py
        pytest tests/test_id.py
        pytest tests/test_location.py
