name: Tests

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '0 8 * * 1' # Schedule to run at 8 AM on Mondays
    - cron: '0 8 * * 3' # Schedule to run at 8 AM on Wednesdays
  pull_request:
    branches:
      - '*'

jobs:
  run_tests:
    strategy:
      matrix:
        test_type:
          - episode
          - id
          - location
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.12

    - name: Install dependencies from requirements.txt
      run: pip install -r requirements.txt

    - name: Run tests for R&M
      run: pytest tests/test_${{ matrix.test_type }}.py
